-- Inserción de 20 grupos con claves representativas y usando IDs directos para nivelAcademico
INSERT INTO grupos (idGrupo, nombreGrupo, estatusGrupo, cicloEscolar, anioGeneracion, carrera, idInstitucion, idNivelAcademico) VALUES
(uuid(), 'G1_ISC', TRUE, '2025-2026', 2025, 'Ingeniería en Sistemas Computacionales', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad Nacional Autónoma de México'), 3),
(uuid(), 'G2_II', TRUE, '2025-2026', 2025, 'Ingeniería Industrial', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Tecnológico de Monterrey'), 3),
(uuid(), 'G3_DERE', TRUE, '2025-2026', 2025, 'Derecho', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad Autónoma Metropolitana'), 3),
(uuid(), 'G4_ARQ', TRUE, '2025-2026', 2025, 'Arquitectura', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad de Guadalajara'), 3),
(uuid(), 'G5_MED', TRUE, '2025-2026', 2025, 'Medicina', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad Anáhuac'), 3),
(uuid(), 'G6_CON', TRUE, '2025-2026', 2025, 'Contaduría', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Instituto Politécnico Nacional'), 3),
(uuid(), 'G7_PSI', TRUE, '2025-2026', 2025, 'Psicología', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad Iberoamericana'), 3),
(uuid(), 'G8_IE', TRUE, '2025-2026', 2025, 'Ingeniería Electrónica', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad Autónoma de Nuevo León'), 3),
(uuid(), 'G9_NI', TRUE, '2025-2026', 2025, 'Negocios Internacionales', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Escuela Bancaria y Comercial'), 3),
(uuid(), 'G10_CC', TRUE, '2025-2026', 2025, 'Ciencias de la Computación', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad de Monterrey'), 3),
(uuid(), 'G11_IM', TRUE, '2025-2026', 2025, 'Ingeniería Mecánica', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad Nacional Autónoma de México'), 1),
(uuid(), 'G12_ECO', TRUE, '2025-2026', 2025, 'Economía', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Tecnológico de Monterrey'), 1),
(uuid(), 'G13_BIO', TRUE, '2025-2026', 2025, 'Biología', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad Autónoma Metropolitana'), 1),
(uuid(), 'G14_IC', TRUE, '2025-2026', 2025, 'Ingeniería Civil', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad de Guadalajara'), 1),
(uuid(), 'G15_FIL', TRUE, '2025-2026', 2025, 'Filosofía', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad Anáhuac'), 2),
(uuid(), 'G16_ANT', TRUE, '2025-2026', 2025, 'Antropología', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Instituto Politécnico Nacional'), 2),
(uuid(), 'G17_QUI', TRUE, '2025-2026', 2025, 'Química', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad Iberoamericana'), 2),
(uuid(), 'G18_MAT', TRUE, '2025-2026', 2025, 'Matemáticas', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Universidad Autónoma de Nuevo León'), 2),
(uuid(), 'G19_HIS', TRUE, '2025-2026', 2025, 'Historia', (SELECT idInstitucion FROM institucion WHERE nombreInstitucion = 'Escuela Bancaria y Comercial'), 2);
